name: Deploy to Raspberry Pi

on:
  push:
    branches: [ "main" ] # branch name

jobs:
  deploy:
    runs-on: self-hosted # Raspberry Pi(Runner)

    steps:
    - name: 1. Pull Latest Code
      run: |
        cd ~/apps/fullportfolio
        git pull origin main

    - name: 2. Install Root Dependencies
      run: |
        cd ~/apps/fullportfolio
        npm install

    - name: 3. Build Frontend
      run: |
        cd ~/apps/fullportfolio/portfolio
        npm install
        npm run build

    - name: 4. Restart Server
      run: |
        pm2 restart fullportfolio